apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/instance: flux-system
    app.kubernetes.io/version: latest
  name: team-workspace
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: dev-podinfo-config
  namespace: team-workspace
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/cdavisafc/dev-podinfo-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: app-gitops-pipelines
  namespace: team-workspace
spec:
  interval: 10m0s
  path: ./gitops-pipelines
  prune: true
  sourceRef:
    kind: GitRepository
    name: dev-podinfo-config
  validation: client
