---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: webapp
  namespace: team-workspace
spec:
  interval: 10m0s
  path: ./webapp
  prune: true
  sourceRef:
    kind: GitRepository
    name: dev-podinfo-config
  validation: client
